import { type } from 'arktype';

// ArkType parse schema
// explicit object-array schemas for all other datasets to avoid 'unknown'.
export const parseSchema = type({
	// Core content
	posts: type({
		id: 'string',
		permalink: 'string',
		date: 'Date',
		created_utc: 'Date',
		ip: 'string | undefined',
		subreddit: 'string',
		gildings: 'number | undefined',
		title: 'string | undefined',
		url: 'string | undefined',
		body: 'string | undefined',
	}).array(),
	post_headers: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		date: 'Date | undefined',
		ip: 'string | undefined',
		subreddit: 'string | undefined',
		gildings: 'number | undefined',
		url: 'string | undefined',
	}).array(),
	comments: type({
		id: 'string',
		permalink: 'string',
		date: 'Date',
		created_utc: 'Date',
		ip: 'string | undefined',
		subreddit: 'string',
		gildings: 'number | undefined',
		link: 'string',
		post_id: 'string | undefined',
		parent: 'string | undefined',
		body: 'string | undefined',
		media: 'string | undefined',
	}).array(),
	comment_headers: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		date: 'Date | undefined',
		ip: 'string | undefined',
		subreddit: 'string | undefined',
		gildings: 'number | undefined',
		link: 'string | undefined',
		parent: 'string | undefined',
	}).array(),

	// Votes / visibility / saves
	post_votes: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		direction: 'string | undefined',
	}).array(),
	comment_votes: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		direction: 'string | undefined',
	}).array(),
	saved_posts: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
	}).array(),
	saved_comments: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
	}).array(),
	hidden_posts: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
	}).array(),

	// Messaging
	message_headers: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		thread_id: 'string | undefined',
		date: 'Date | undefined',
		ip: 'string | undefined',
		from: 'string | undefined',
		to: 'string | undefined',
	}).array(),
	messages: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		thread_id: 'string | undefined',
		date: 'Date | undefined',
		ip: 'string | undefined',
		from: 'string | undefined',
		to: 'string | undefined',
		subject: 'string | undefined',
		body: 'string | undefined',
	}).array(),
	messages_archive_headers: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		thread_id: 'string | undefined',
		date: 'Date | undefined',
		ip: 'string | undefined',
		from: 'string | undefined',
		to: 'string | undefined',
	}).array(),
	messages_archive: type({
		id: 'string | undefined',
		permalink: 'string | undefined',
		thread_id: 'string | undefined',
		date: 'Date | undefined',
		ip: 'string | undefined',
		from: 'string | undefined',
		to: 'string | undefined',
		subject: 'string | undefined',
		body: 'string | undefined',
	}).array(),

	// Chat
	chat_history: type({
		message_id: 'string | undefined',
		created_at: 'Date | undefined',
		updated_at: 'Date | undefined',
		username: 'string | undefined',
		message: 'string | undefined',
		thread_parent_message_id: 'string | undefined',
		channel_url: 'string | undefined',
		subreddit: 'string | undefined',
		channel_name: 'string | undefined',
		conversation_type: 'string | undefined',
	}).array(),

	// Account and preferences
	account_gender: type({ account_gender: 'string | undefined' }).array(),
	sensitive_ads_preferences: type({
		type: 'string | undefined',
		preference: 'string | undefined',
	}).array(),
	birthdate: type({
		birthdate: 'Date | undefined',
		verified_birthdate: 'Date | undefined',
		verification_state: 'string | undefined',
		verification_method: 'string | undefined',
	}).array(),
	user_preferences: type({
		preference: 'string | undefined',
		value: 'string | undefined',
	}).array(),
	linked_identities: type({
		issuer_id: 'string | undefined',
		subject_id: 'string | undefined',
	}).array(),
	linked_phone_number: type({ phone_number: 'string | undefined' }).array(),
	twitter: type({ username: 'string | undefined' }).array(),

	// Moderation / subscriptions / subreddits
	approved_submitter_subreddits: type({
		subreddit: 'string | undefined',
	}).array(),
	moderated_subreddits: type({ subreddit: 'string | undefined' }).array(),
	subscribed_subreddits: type({ subreddit: 'string | undefined' }).array(),
	multireddits: type({
		id: 'string | undefined',
		display_name: 'string | undefined',
		date: 'Date | undefined',
		description: 'string | undefined',
		privacy: 'string | undefined',
		subreddits: 'string | undefined',
		image_url: 'string | undefined',
		is_owner: 'string | undefined',
		favorited: 'string | undefined',
		followers: 'string | undefined',
	}).array(),

	// Commerce and payouts
	purchases: type({
		processor: 'string | undefined',
		transaction_id: 'string | undefined',
		product: 'string | undefined',
		date: 'Date | undefined',
		cost: 'string | undefined',
		currency: 'string | undefined',
		status: 'string | undefined',
	}).array(),
	subscriptions: type({
		processor: 'string | undefined',
		subscription_id: 'string | undefined',
		product: 'string | undefined',
		product_id: 'string | undefined',
		product_name: 'string | undefined',
		status: 'string | undefined',
		start_date: 'Date | undefined',
		end_date: 'Date | undefined',
	}).array(),
	payouts: type({
		payout_amount_usd: 'string | undefined',
		date: 'Date | undefined',
		payout_id: 'string | undefined',
	}).array(),
	stripe: type({ stripe_account_id: 'string | undefined' }).array(),

	// Misc
	announcements: type({
		announcement_id: 'string | undefined',
		sent_at: 'Date | undefined',
		read_at: 'Date | undefined',
		from_id: 'string | undefined',
		from_username: 'string | undefined',
		subject: 'string | undefined',
		body: 'string | undefined',
		url: 'string | undefined',
	}).array(),
	drafts: type({
		id: 'string | undefined',
		title: 'string | undefined',
		body: 'string | undefined',
		kind: 'string | undefined',
		created: 'Date | undefined',
		spoiler: 'string | undefined',
		nsfw: 'string | undefined',
		original_content: 'string | undefined',
		content_category: 'string | undefined',
		flair_id: 'string | undefined',
		flair_text: 'string | undefined',
		send_replies: 'string | undefined',
		subreddit: 'string | undefined',
		is_public_link: 'string | undefined',
	}).array(),
	friends: type({
		username: 'string | undefined',
		note: 'string | undefined',
	}).array(),
	gilded_content: type({
		content_link: 'string | undefined',
		award: 'string | undefined',
		amount: 'string | undefined',
		date: 'Date | undefined',
	}).array(),
	gold_received: type({
		content_link: 'string | undefined',
		gold_received: 'string | undefined',
		gilder_username: 'string | undefined',
		date: 'Date | undefined',
	}).array(),
	ip_logs: type({ date: 'Date | undefined', ip: 'string | undefined' }).array(),
	persona: type({ persona_inquiry_id: 'string | undefined' }).array(),
	poll_votes: type({
		post_id: 'string | undefined',
		user_selection: 'string | undefined',
		text: 'string | undefined',
		image_url: 'string | undefined',
		is_prediction: 'string | undefined',
		stake_amount: 'string | undefined',
	}).array(),
	scheduled_posts: type({
		scheduled_post_id: 'string | undefined',
		subreddit: 'string | undefined',
		title: 'string | undefined',
		body: 'string | undefined',
		url: 'string | undefined',
		submission_time: 'Date | undefined',
		recurrence: 'string | undefined',
	}).array(),
	statistics: type({
		statistic: 'string | undefined',
		value: 'string | undefined',
	}).array(),
	checkfile: type({
		filename: 'string | undefined',
		sha256: 'string | undefined',
	}).array(),
});
