name: build-windows
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tauri:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './apps/whispering/src-tauri -> target'

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: install frontend deps
        run: bun install

      - name: build frontend
        run: bun --filter @repo/whispering build

      # Use tauri-action just to build (no release metadata/notes/signing)
      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: 'apps/whispering'
          args: ''  # no special target for Windows
        env:
          CI: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            apps/whispering/src-tauri/target/release/*.exe
            apps/whispering/src-tauri/target/**/bundle/**/*.msi
            apps/whispering/src-tauri/target/**/bundle/**/*.exe
          retention-days: 14
